# Generated by Django 2.1 on 2018-10-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.RenameField(
            model_name='valor',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
