# Generated by Django 2.1 on 2018-10-05 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20181005_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='valor',
            old_name='nombres',
            new_name='nombre',
        ),
    ]
